/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Listas.java
 *
 * Created on 09/10/2011, 23:00:06
 */

package br.ufrn.controleinteligente.gui;

import br.ufrn.controleinteligente.estruturas.Labirinto;
import br.ufrn.controleinteligente.estruturas.No;
import java.util.Iterator;

/**
 *
 * @author Andre
 */
public class Listas extends javax.swing.JFrame {

    private Labirinto labirinto;

    
    private void imprimeListas(){
        String nosAbertos = "";
        Iterator it2 = labirinto.getAbertos().iterator();
                nosAbertos="Abertos:";
                while (it2.hasNext()) {
                    if(!nosAbertos.equals("Abertos:"))
                        nosAbertos+=",";
                    No noS = (No) it2.next();
                    nosAbertos+="("+noS.getX()+","+noS.getY()+")";
                }
        System.out.println(nosAbertos);
      lbAbertos.setText(nosAbertos);

      it2 = labirinto.getFechados().iterator();
                nosAbertos="Fechados:";
                while (it2.hasNext()) {
                    if(!nosAbertos.equals("Fechados:"))
                        nosAbertos+=",";
                    No noS = (No) it2.next();
                    nosAbertos+="("+noS.getX()+","+noS.getY()+")";
                }
        System.out.println(nosAbertos);
      lbFechados.setText(nosAbertos);

      it2 = labirinto.getSolucao().iterator();
                nosAbertos="Solução:";
                while (it2.hasNext()) {
                    if(!nosAbertos.equals("Solução:"))
                        nosAbertos+=",";
                    No noS = (No) it2.next();
                    nosAbertos+="("+noS.getX()+","+noS.getY()+")";
                }
    System.out.println(nosAbertos);
      lbSolucao.setText(nosAbertos);
    }

    /** Creates new form Listas */
    public Listas(java.awt.Frame parent, boolean modal, Labirinto labirinto) {
        this.labirinto = labirinto;
        initComponents();
        imprimeListas();
        super.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbAbertos = new javax.swing.JLabel();
        lbFechados = new javax.swing.JLabel();
        lbSolucao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Labirinto");

        lbAbertos.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 11));
        lbAbertos.setText("Abertos:");

        lbFechados.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 11)); // NOI18N
        lbFechados.setText("Fechados:");

        lbSolucao.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 11));
        lbSolucao.setText("Solução:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbSolucao)
                    .addComponent(lbFechados)
                    .addComponent(lbAbertos))
                .addContainerGap(1180, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbAbertos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbFechados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbSolucao)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbAbertos;
    private javax.swing.JLabel lbFechados;
    private javax.swing.JLabel lbSolucao;
    // End of variables declaration//GEN-END:variables

}
